discordx-ts/discordx

- docs/docs/decorators/general/guard.md
Guard Functions documentation has incorrect example of  `GuardDatas` usage. It don't use `guardDatas` variable at all!
This PR corrects documentation by adding missing code from [old DiscordTS Docs](https://owencalvin.github.io/discord.ts/decorators/guard.html#guard-datas)
Incorrect examples in documentation confuses developers
> Fix GuardDatas Incorrect Example

- packages/music/src/YoutubePlayer/tracks/CustomTrack.ts
enable inlineVolume in createAudioResource so that `.setVolume` works
- @discordx/music
> fix: .setVolume() not working in custom tracks

- packages/music/src/YoutubePlayer/core/Queue.ts
Currently, the volume is not being persisted between tracks, this should fix it.
Already tested this fix and worked without any problem.
- @discordx/music
> fix: volume should persist between tracks

- packages/discordx/README.md
Just a couple of broken documentation links
- discordx
> chore(discordx): fix broken links in readme

- packages/discordx/src/decorators/classes/DApplicationCommand.ts
fix the import of the "discord-api-types" package which requires to specify the API version to use. Unable to launch with Docker if not specified.
Fixes #648
- discordx
> refactor: use specific version of discord api (discord-api-types)

- packages/utilities/examples/guards/commands/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/logic/TimedSet.ts
- packages/utilities/src/guards/Rate Limiter/logic/Timer.ts
- packages/utilities/src/guards/Rate Limiter/logic/index.ts
- packages/utilities/src/guards/Rate Limiter/types/ITimedSet.ts
Added the ability to be able to inject the time in which the next execution is in the custom message via {until} in the format `<t:epoch:T>`
While i could have made callback to "format" the message. it's not worth it, i think `<t:T>` is fine for this use case
@discordx/utilities
> feat: include a custom message placeholder for time remaining

- packages/discordx/src/Client.ts
As discussed in issue #697, this changes application command updates from using `n` requests to `1` request*. This will fix rate limits simply by not making nearly as many requests.
Note: 1 request per guild and 1 request for global commands, there seems to be no way around having to do a request per guild.
- discordx
> refactor: init applications - use set operation

- packages/utilities/examples/guards/commands/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/RateLimit.ts
Another rate-limit feature i am afraid 😅
In order to support multi-lingual localisation, i have included the ability to resolve the rate limit message via a resolver that passes both the interaction and how many milliseconds are left until the rate limit is over
@discordx/utilities
> feat: rate limit message now includes a resolver

- packages/importer/package.json
This PR fixes an issue in `@discordx/importer` where, if you configured your `tsconfig.json` to use `NodeNext` module resolution, the types will not be located by tsc. This is because upon enabling `NodeNext`, tsc no longer falls back to the root `types` declaration. Both declarations are required for full ESM compatibility.
- @discordx/importer
> fix: @discordx/importer ESM exports

- docs/docs/decorators/commands/slash-choice.md
Fixing a little mistake in the documentation of SlashChoiceType
`docs`
> docs: syntax SlashChoicesType to SlashChoiceType

- packages/lava-player/src/base/Node.ts
- packages/lava-player/src/core/Player.ts
Previously lava-player only stored the session id of the VoiceStateUpdate event, it is useful for internal stuff but when you want to know more about the current player's voice state it is not so useful. What this does is to save the complete payload of the VoiceStateUpdate event and be able to get it in the player.
Note: It was supposed to be this way because of the types that the Player class has.
@discordx/lava-player
> fix(lava-player): the VoiceStateUpdate event payload was not completely saved

- .github/CONTRIBUTING.md
Update `CONTRIBUTING.md` to use main like the actual repository instead of master
> docs: update contributing to use main instead of master

- packages/lava-queue/src/queue.ts
Currently the search method has the search engine hardcoded, with this change you can choose what search engine to use and keep `ytsearch` as the default value
@discordx/lava-queue
- discordx
- @discordx/lava-queue
> refactor: remove lava link hard coded search prefix

- packages/discordx/tests/slash.test.ts
This pull request adds a currently failing test to demonstrate that duplicate subgroups are currently going wrong. This does not have to be merged, this is mostly to provide a failing test for the issue I'm having.
With this added logic, the library should generate the following:
```
/test-x m
/test-x n
/test-x add y
/test-x add x
/test-y o
/test-y p
/test-y add y
/test-y add z
```
However at the time of the pull request the following is produced:
```
/test-x m
/test-x n
/test-x add z
/test-x add y
/test-x add y
/test-x add x
/test-y o
/test-y p
```
- discordx
> Add test for duplicate command groups

- packages/lava-queue/src/queue.ts
Currently if the queue is both on loop and on repeat, it keeps adding the song to the end of queue instead of just adding it to the beginning of the queue
- @discordx/lava-queue
> fix(lava-queue): do not add song to the end of queue

- packages/utilities/src/guards/NotBot/index.ts
This fix allows the user to be undefined, which still meets the intent of the guard.
#904 
This will fix a bug using discordx global guards and discordx emitter decorators.
> fix(utilities): emitter decorator does not contain user obj

- docs/docs/discordx/basics/plugin.md
- packages/discordx/examples/plugin/main.ts
- packages/discordx/examples/plugin/plugin/commands/help.ts
- packages/discordx/examples/plugin/plugin/plugin.ts
- packages/discordx/examples/plugin/tsconfig.json
- packages/discordx/src/Client.ts
- packages/discordx/src/logic/index.ts
- packages/discordx/src/logic/plugin.ts
- packages/discordx/src/types/core/ClientOptions.ts
Develop plugins for discordx. You can publish your plugin on NPM. Maintain a single codebase while using them on different bots.
```ts
import { dirname, importx } from "@discordx/importer";
import { Plugin } from "discordx";
export class HelperPlugin extends Plugin {
async init(): Promise<void> {
// This section is similar to the bot login section. However, here we are doing this for a plugin.
await importx(`${dirname(import.meta.url)}/commands/**/*.{js,ts}`);
}
}
```
```ts
import { Client, MetadataStorage } from "discordx";
// Initialize the plugin
const helperPlugin = new HelperPlugin({ metadata: MetadataStorage.instance });
// Provide plugins to client
new Client({ plugins: [helperPlugin] });
```
> feat(discordx): plugins support

- .gitattributes
- .prettierrc.json
- packages/discordx/src/decorators/classes/DApplicationCommand.ts
- packages/discordx/src/decorators/decorators/Slash.ts
- packages/discordx/src/types/public/slash.ts
- packages/discordx/src/util/comparison.ts
Added `nsfw` option to slash decorator to match [discord api types](https://discord-api-types.dev/api/discord-api-types-v10/interface/APIApplicationCommand)
- discordx
> refactor(discordx): add nsfw option to slash command objs

- .gitattributes
- .prettierrc.json
- packages/discordx/src/decorators/classes/DApplicationCommand.ts
- packages/discordx/src/decorators/decorators/Slash.ts
- packages/discordx/src/types/public/slash.ts
- packages/discordx/src/util/comparison.ts
Added `nsfw` option to slash decorator to match [discord api types](https://discord-api-types.dev/api/discord-api-types-v10/interface/APIApplicationCommand)
- discordx
> refactor(discordx): add nsfw to main branch

- packages/discordx/src/decorators/classes/DApplicationCommand.ts
- packages/discordx/src/types/public/slash.ts
- packages/discordx/tests/slash-choice.test.ts
- packages/discordx/tests/slash-group.test.ts
- packages/discordx/tests/slash.test.ts
Adds missing nsfw property to obj that hits discord
- discordx
> fix(discordx): add missing nsfw prop to json

- docs/docs/discordx/basics/dependencyInjection.md
- packages/di/src/logic/impl/TsyringeDependencyRegistryEngine.ts
- packages/di/src/logic/impl/TypeDiDependencyRegistryEngine.ts
- packages/discordx/examples/di/tsyringe/commands/TokenInjection.ts
- packages/discordx/examples/di/tsyringe/commands/common.ts
DI tokenization was broken, well, more hacked than broken for Tsyringe. It was a long time coming, but we needed a way that we can resolve tokenized items from the registry without dual singleton creation when wanting to get the same item from the container.
I originally created a method to get items and filter them each time. this imposed multiple issues:
- it's slow
- it caused ALL discordx dependancies to be resolved every time they where asked
- it broke lazy loading
In order to solve this issue, i created an `Instance Cashing Singleton Factory` that, when an item from a token is resolved, would register the same token via the singleton factory and return that same item back to the container, effectivally registerting the class in BOTH the symbol and the constructor as a token. 
This …
> chore(di): fix tokenization injection

- docs/docs/discordx/basics/dependencyInjection.md
- packages/di/src/logic/impl/TsyringeDependencyRegistryEngine.ts
the change i made brang in the `container` that wasn't from a `import type` this caused issues with people using the Default DI method as tsyringe was trying to load and required `reflect-metadata`
this addresses this issue
> fix(di): when no di method used, exception was thrown

- packages/discordx/examples/di/typedi/tsconfig.json
Set `emitDecoratorMetadata` to true because typedi requires it to be true, provides a better reference for example.
- discordx
> fix: typedi example tsconfig.json

- .github/CONTRIBUTING.md
some hyperlinks are broken in [CONTRIBUTING.md](https://github.com/discordx-ts/discordx/blob/main/.github/CONTRIBUTING.md).
if those syntaxes should work, they should have their own link URL like [CODE_OF_CONDUCT.md](https://github.com/discordx-ts/discordx/blob/main/.github/CODE_OF_CONDUCT.md?plain=1#L124)
so I added URLs as possible as many, but not all of them because I could not find them.
* [coc]: seems like just #coc heading link.
* [github]: *our [GitHub Repository]* means this repository.
* [js-style-guide]: couldn't find it in this repository, so I searched and got [jsguide.html](https://google.github.io/styleguide/jsguide.html)
* [commit-message-format]: seems similar to …
> doc: reconnect minlinked links as possible as many

- packages/di/CHANGELOG.md
- packages/di/examples/tsyringe/main.ts
- packages/di/package.json
- packages/di/src/index.ts
- packages/di/src/logic/AbstractConfigurableDependencyInjector.ts
- packages/di/src/logic/IDependencyRegistryEngine.ts
- packages/di/src/logic/impl/DefaultDependencyRegistryEngine.ts
- packages/di/src/logic/impl/TsyringeDependencyRegistryEngine.ts
- packages/di/src/logic/impl/TypeDiDependencyRegistryEngine.ts
They store singleton instances of class.
- Default: A simple `Map` for singleton classes.
- TSyringe
- TypeDI
A engine method, that allow cleanup for supported dependency engines.
> refactor(di): added clearAllServices method for engine and updated DIService to act as bridge for engine only

- .changeset/config.json
- package.json
Switches Changesets to use  [@changesets/changelog-github](https://github.com/changesets/changesets/tree/main/packages/changelog-github) which passes a lot more information retaining to GitHub to the CHANGELOGS and GitHub releases.
With and Without using changelog-github:
- [with](https://github.com/changesets/changesets/blob/main/packages/cli/CHANGELOG.md) vs [without](https://github.com/discordx-ts/discordx/blob/main/packages/discordx/CHANGELOG.md)
- [with](https://github.com/changesets/changesets/releases/tag/%40changesets%2Fcli%402.27.0) vs [without](https://github.com/discordx-ts/discordx/releases/tag/music-6.0.0)
> ci: use changesets changelog-github

- docs/docs/discordx/decorators/command/slash-option.md
- docs/docs/discordx/decorators/general/bot.md
- docs/docs/discordx/decorators/general/guard.md
- docs/docs/discordx/decorators/general/guild.md
- docs/docs/discordx/decorators/general/once.md
Fix various links that result in `docs/discordx/*/*/*/docs/discordx/*/*/*` instead of `docs/discordx/*/*/*`
> docs: fix various broken links

- .changeset/real-phones-sit.md
- package-lock.json
- packages/utilities/README.md
- packages/utilities/package.json
- packages/utilities/src/useful/index.ts
- packages/utilities/src/useful/time-format.ts
Discord timestamps can be useful for specifying a date/time across multiple users time zones. They work with the Unix Timestamp format and can be posted by regular users as well as bots and applications.
[The Epoch Unix Time Stamp Converter](https://www.unixtimestamp.com/) is a good way to quickly generate a timestamp. For the examples below I will be using the Time Stamp of `1543392060`, which represents `November 28th, 2018` at `09:01:00` hours for my local time zone (GMT+0100 Central European Standard Time).
| Syntax                        | Output             | Output (12-hour clock)               | Output (24-hour clock)            |
| ----------------------------- | ------------------ | ------------------------------------ | --------------------------------- |
| TimeFormat.Default …
> feat(utilities): time format

- .changeset/rare-birds-matter.md
- packages/utilities/README.md
- packages/utilities/examples/guards/commands/PermissionGuards.ts
- packages/utilities/examples/guards/commands/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/types/common.ts
- packages/utilities/src/useful/time-format.ts
I think a much more user-friendly option is to use relative timestamps, it makes more sense to say you can use the command in 5 seconds, or in 6 hours, instead of telling the user that you can use it at 6:42 PM.
On the other hand I'm not sure if this change is to be merged as is, it's meant to start a discussion:
* Does the noun `until` still make any sense here after the change?
* Maybe we could add another substitution like `{time}` or `{duration}` and keep `{until}` as is, this will preserve backward compatibility with existing code while giving an option to use this relative notation for those who desires it.
* If we go with that, I'd still choose the relative notation to be the default option as it makes more sense.
* I would also choose to refactor the default reply message as it …
> refactor(utilities): Use relative timestamps

- docs/docs/discordx/decorators/command/slash-option.md
- package-lock.json
- packages/discordx/CHANGELOG.md
- packages/discordx/examples/builders/commands/autocomplete.ts
- packages/discordx/examples/builders/commands/choice.ts
- packages/discordx/examples/builders/commands/hello.ts
- packages/discordx/examples/builders/commands/ping.ts
- packages/discordx/examples/builders/main.ts
- packages/discordx/examples/builders/tsconfig.json
- packages/discordx/examples/slash/commands/transformer.ts
- packages/discordx/package.json
- packages/discordx/src/decorators/classes/DApplicationCommand.ts
- packages/discordx/src/decorators/classes/DApplicationCommandOption.ts
- packages/discordx/src/decorators/decorators/Slash.ts
- packages/discordx/src/decorators/decorators/SlashOption.ts
- packages/discordx/src/types/public/slash.ts
- packages/plugin-lava-player/package.json
- packages/utilities/package.json
Example
```ts
import {
SlashCommandBuilder,
SlashCommandMentionableOption,
User,
type CommandInteraction,
} from "discord.js";
import { Discord, Slash, SlashOption } from "discordx";
const cmd = new SlashCommandBuilder()
.setName("hello")
.setDescription("Say hello!");
const user_option = new SlashCommandMentionableOption()
.setName("user")
.setDescription("Mention user to say hello to.")
.setRequired(true);
@Discord()
export class Example {
@Slash(cmd)
async hello(
@SlashOption(user_option) user: User,
interaction: CommandInteraction,
): Promise<void> {
await interaction.reply(`:wave: ${user}`);
}
}
```
> refactor(discordx): discordjs builders support

- packages/lava-queue/CHANGELOG.md
- packages/lava-queue/package.json
- packages/lava-queue/src/queue.ts
- packages/music/CHANGELOG.md
- packages/music/package.json
- packages/music/src/queue.ts
- packages/plugin-lava-player/CHANGELOG.md
- packages/plugin-lava-player/package.json
- packages/plugin-ytdl-player/CHANGELOG.md
- packages/plugin-ytdl-player/package.json
- packages/plugin-ytdl-player/src/core/queue.ts
- packages/plugin-ytdl-player/src/utils/queue.ts
- Repeat mode does not work if the queue is empty, even if there is a track playing.
- The `REPEAT_ONE` is repeating all tracks instead of only the current track.
> fix: track repeat modes

- packages/discordx/CHANGELOG.md
- packages/discordx/package.json
- packages/discordx/src/logic/metadata/MetadataStorage.ts
**Please describe the changes this PR makes:**
The trigger creates a "trigger" function which saves the context into the _listeners map in the client.
Each time this function get's triggered the response is pushed into the responses array, which is created once, on startup. This causes a memory leak which saves all responses during the lifetime of the bot.
By moving the respones array into the function itself this is resolved and it will only return the responses for that specific trigger and the array can be garbage collected after this.
For a quick example of this bug on production (running for around a week with 100k members):
This array uses about 250 MB of memory, which is about 90% of all memory usage, and the array only contains empty objects returned from the execute function.
> fix: memory leak in event triggers
