- docs/docs/decorators/general/guard.md
> minor changes

- docs/i18n/fr/docusaurus-plugin-content-docs/current/installation.mdx
> French translation of Installation

- docs/docs/decorators/commands/slashoption.md
- examples/slash/discords/AppDiscord.ts
- src/Client.ts
- src/decorators/classes/DApplicationCommandOption.ts
- src/decorators/decorators/SlashOption.ts
- src/decorators/params/SlashOptionParams.ts
- tests/slash.test.ts
> feat: autocomplete

- .eslintrc
- .github/workflows/Builld.yml
- .github/workflows/Publish - Stable.yml
- package.json
- packages/importer/LICENSE
- packages/importer/README.md
- packages/importer/package-lock.json
- packages/importer/package.json
- packages/importer/src/cjs/index.cts
- packages/importer/src/esm/index.mts
- packages/importer/tests/commands/demo.js
- packages/importer/tests/index.cjs
- packages/importer/tests/index.mjs
- packages/importer/tsconfig.cjs.json
- packages/importer/tsconfig.json
- packages/music/package.json
- packages/utilities/package.json
- scripts/changelog.mjs
> feat: new package @discordx/importer

- docs/docs/decorators/commands/slashchoice.md
- docs/docs/decorators/commands/slashoption.md
- examples/slash/discords/AppDiscord.ts
- packages/music/examples/LavalinkPlayer/discords/AppDiscord.ts
- packages/music/examples/YoutubePlayer/discords/AppDiscord.ts
- src/decorators/classes/DApplicationCommandOption.ts
- src/decorators/decorators/SlashOption.ts
- tests/slash.test.ts
Set slash option required true by default
- discordx
> BREAKING CHANGE: set slash option required by default

- docs/package.json
Reverts oceanroleplay/discord.ts#486
> Revert "build(deps): bump @mdx-js/react from 1.6.22 to 2.0.0 in /docs"

- packages/utilities/README.md
- packages/utilities/examples/guards/discords/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/TimeOutEntry.ts
- packages/utilities/src/guards/Rate Limiter/index.ts
- packages/utilities/src/guards/Rate Limiter/types.ts
This PR adds a guard that can be applied to commands to rate limit them.
This will add the ability to rate limit commands
Added:
Example
Docs
The Guard
TimedSet util class that is a set with a timer on each element
> feat: added util guard Rate Limit commands

- docs/docs/general/tsyringe.md
Super small doc update to clarify where DIService is coming from, had me scratching my head for a bit before I looked further down in the docs.
- discordx
> docs: Clarify DIService import for tsyringe docs

- docs/docs/decorators/commands/slashchoice.md
- docs/docs/decorators/commands/slashgroup.md
- packages/discordx/examples/slash/commands/group.ts
- packages/discordx/src/decorators/decorators/SlashGroup.ts
- packages/discordx/src/logic/metadata/MetadataStorage.ts
- packages/discordx/src/types/public/CommandType.ts
- packages/discordx/tests/slash.test.ts
#508 
```ts
@Discord()
export abstract class Group1 {
@Slash("cars2")
@SlashGroup({ name: "mytools", root: "tools" })
voicechannel(interaction: CommandInteraction): void {
interaction.reply("cmd 1");
}
}
@Discord()
@SlashGroup({ name: "tools" })
@SlashGroup({ name: "mytools", root: "tools" })
export abstract class Group {
@Slash("cars")
@SlashGroup({ name: "mytools", root: "tools" })
voicechannel(interaction: CommandInteraction): void {
interaction.reply("cmd 1");
}
}
```
> refactor: slash group

- docs/docs/decorators/commands/slashgroup.md
- packages/discordx/examples/slash/commands/group.ts
- packages/discordx/examples/slash/commands/group2.ts
- packages/discordx/src/decorators/decorators/Bot.ts
- packages/discordx/src/decorators/decorators/ButtonComponent.ts
- packages/discordx/src/decorators/decorators/ContextMenu.ts
- packages/discordx/src/decorators/decorators/Discord.ts
- packages/discordx/src/decorators/decorators/Guard.ts
- packages/discordx/src/decorators/decorators/Guild.ts
- packages/discordx/src/decorators/decorators/On.ts
- packages/discordx/src/decorators/decorators/Once.ts
- packages/discordx/src/decorators/decorators/Permission.ts
- packages/discordx/src/decorators/decorators/SelectMenuComponent.ts
- packages/discordx/src/decorators/decorators/SimpleCommand.ts
- packages/discordx/src/decorators/decorators/SimpleCommandOption.ts
- packages/discordx/src/decorators/decorators/Slash.ts
- packages/discordx/src/decorators/decorators/SlashChoice.ts
- packages/discordx/src/decorators/decorators/SlashGroup.ts
- packages/discordx/src/decorators/decorators/SlashOption.ts
- packages/discordx/src/types/public/CommandType.ts
```ts
@Discord()
@SlashGroup({ name: "testx" })
@SlashGroup({ appendToChild: true, name: "add", root: "testx" })
export abstract class Group {
@Slash()
x(interaction: CommandInteraction): void {
interaction.reply(":wave:");
}
@Slash()
y(interaction: CommandInteraction): void {
interaction.reply(":wave:");
}
}
@Discord()
@SlashGroup({ appendToChild: true, name: "testx" })
export abstract class AnotherGroup {
@Slash()
m(interaction: CommandInteraction): void {
interaction.reply(":wave:");
}
@Slash()
n(interaction: CommandInteraction): void {
interaction.reply(":wave:");
}
}
```
> refactor: append group option

- docs/docs/decorators/commands/slashgroup.md
- packages/discordx/examples/slash/commands/group.ts
- packages/discordx/examples/slash/commands/group2.ts
- packages/discordx/src/decorators/decorators/SlashGroup.ts
- packages/discordx/src/types/public/CommandType.ts
- packages/discordx/tests/slash.test.ts
New way to assign groups to child aka slashes.
> refactor: group

- packages/discordx/src/Client.ts
- packages/discordx/src/decorators/classes/Method.ts
- packages/discordx/src/decorators/decorators/Bot.ts
- packages/discordx/src/decorators/decorators/ButtonComponent.ts
- packages/discordx/src/decorators/decorators/ContextMenu.ts
- packages/discordx/src/decorators/decorators/Guild.ts
- packages/discordx/src/decorators/decorators/On.ts
- packages/discordx/src/decorators/decorators/Once.ts
- packages/discordx/src/decorators/decorators/Permission.ts
- packages/discordx/src/decorators/decorators/SelectMenuComponent.ts
- packages/discordx/src/decorators/decorators/SimpleCommand.ts
- packages/discordx/src/decorators/decorators/SimpleCommandOption.ts
- packages/discordx/src/decorators/decorators/Slash.ts
- packages/discordx/src/decorators/decorators/SlashChoice.ts
- packages/discordx/src/decorators/decorators/SlashGroup.ts
- packages/discordx/src/decorators/decorators/SlashOption.ts
- packages/discordx/src/logic/metadata/MetadataStorage.ts
- packages/internal/src/decorator/classes/Modifier.ts
- packages/internal/src/decorator/util.ts
- packages/music/package.json
- packages/music/src/core/Player.ts
- packages/music/src/core/Queue.ts
- packages/music/src/logic/util.ts
- packages/music/src/logic/ytdl.ts
- packages/pagination/src/Pagination.ts
- packages/utilities/README.md
- packages/utilities/examples/guards/discords/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/logic/TimedSet.ts
- packages/utilities/src/guards/Rate Limiter/types/ITimedSet.ts
Update `@params`in overall projects
> refactor: params

- docs/docs/decorators/commands/simplecommandoption.md
- packages/discordx/examples/command/commands/common.ts
- packages/discordx/src/Client.ts
- packages/discordx/src/classes/SimpleCommandMessage.ts
- packages/discordx/src/decorators/classes/DSimpleCommand.ts
- packages/discordx/tests/command.test.ts
> refactor: simplecommand - use fetch instead resolve

- docs/docs/decorators/commands/slashgroup.md
> docs: slash group

- docs/docs/installation.mdx
- packages/discordx/README.md
The old link points to a 404. Seems it wasn't updated for the monorepo structure. 
- discordx
> chore: update examples link

- .gitignore
- docs/CHANGELOG.md
- packages/pagination/CHANGELOG.md
- packages/pagination/README.md
- packages/pagination/examples/pagination/discords/AppDiscord.ts
- packages/pagination/examples/pagination/discords/configurations.ts
- packages/pagination/examples/pagination/discords/slash command info.ts
- packages/pagination/src/Pagination.ts
- packages/pagination/src/functions/GeneratePage.ts
- packages/pagination/src/types.ts
> refactor: pagination

- packages/discordx/examples/slash/commands/permission.ts
- packages/discordx/src/classes/DefaultPermissionResolver.ts
- packages/discordx/src/classes/Mixin/ApplicationCommandMixin.ts
- packages/discordx/src/classes/Mixin/ApplicationGuildMixin.ts
- packages/discordx/src/classes/index.ts
Use Mixin as prefix instead suffix.
> refactor: rename mixin classes

- packages/discordx/src/Client.ts
Fix duplicate event issue after bot restart in runtime.
- discordx
> fix: duplicate event issue

- .github/workflows/Publish - Stable.yml
- packages/create-discordx/LICENSE
- packages/create-discordx/README.md
- packages/create-discordx/package.json
- packages/create-discordx/src/helper/common.ts
- packages/create-discordx/src/helper/git.ts
- packages/create-discordx/src/helper/is-folder-empty.ts
- packages/create-discordx/src/helper/template.ts
- packages/create-discordx/src/helper/updater.ts
- packages/create-discordx/src/index.ts
- packages/create-discordx/tsconfig.json
Creates discordx projects instantly with a command line
```bash
npx create-discordx
```
https://github.com/oceanroleplay/discordx-templates
> feat: create-discordx

- packages/discordx/src/Client.ts
- packages/discordx/src/decorators/classes/DApplicationCommand.ts
- packages/discordx/src/decorators/classes/DComponent.ts
- packages/discordx/src/decorators/classes/DSimpleCommand.ts
> refactor: guild check

- .gitignore
- docs/docs/general/dependencyInjection.md
- docs/sidebars.js
- package.json
- packages/di/package.json
- packages/di/src/index.ts
- packages/discordx/examples/typedi/commands/common.ts
- packages/discordx/examples/typedi/main.ts
- packages/discordx/examples/typedi/tsconfig.json
Added support for Typedi and unified the docs to decouple the IOC documentation from tsyringe to a more generic DI document.
@discordx/di
> feat: added support for typedi and unified the docs

- packages/discordx/README.md
added TypeDI to the list of supported features
discordx
> chore: add typedi to readme

- packages/discordx/src/Client.ts
Since changes only show changed methods, reviewer must check other `.log` calls as well.
- discordx
> refactor: use proper logger method

- packages/lava-player/src/core/Connection.ts
- packages/lava-player/src/types/Event.ts
- packages/lava-player/src/types/http.ts
- packages/lava-queue/LICENSE
- packages/lava-queue/README.md
- packages/lava-queue/SECURITY.md
- packages/lava-queue/examples/commands/music.ts
- packages/lava-queue/examples/main.ts
- packages/lava-queue/examples/package.json
- packages/lava-queue/examples/tsconfig.json
- packages/lava-queue/package.json
- packages/lava-queue/src/index.ts
- packages/lava-queue/src/package.json
- packages/lava-queue/src/player.ts
- packages/lava-queue/src/queue.ts
- packages/lava-queue/tsconfig.json
**Queue system for lava player**
> feat: package - lava-queue

- packages/utilities/README.md
- packages/utilities/examples/guards/commands/PermissionGuards.ts
- packages/utilities/src/guards/PermissionGuard/index.ts
- packages/utilities/src/guards/index.ts
Added Permission guard to easily allow people who use global commands to add role permissions for command execution.
@discordx/utilities
> feat: added Permission guard

- packages/utilities/README.md
- packages/utilities/examples/guards/commands/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/RateLimit.ts
- packages/utilities/src/guards/Rate Limiter/types/common.ts
thje previous commit to this feature failed to update the packages, and also broke the API by not only moving to an object, but also forgetting the props can be optional 
@discordx/utilities
> fix: fixed optional types

- packages/lava-player/src/base/Cluster.ts
> fix(lava-player): cannot get node for players

- docs/docs/decorators/general/reaction.md
- docs/sidebars.js
- packages/discordx/README.md
- packages/discordx/examples/reaction/commands/common.ts
- packages/discordx/examples/reaction/main.ts
- packages/discordx/examples/reaction/tsconfig.json
- packages/discordx/src/Client.ts
- packages/discordx/src/decorators/classes/DDiscord.ts
- packages/discordx/src/decorators/classes/DReaction.ts
- packages/discordx/src/decorators/classes/index.ts
- packages/discordx/src/decorators/decorators/Bot.ts
- packages/discordx/src/decorators/decorators/Guard.ts
- packages/discordx/src/decorators/decorators/Guild.ts
- packages/discordx/src/decorators/decorators/Reaction.ts
- packages/discordx/src/decorators/decorators/index.ts
- packages/discordx/src/logic/metadata/MetadataStorage.ts
- packages/discordx/src/types/core/common.ts
- packages/discordx/src/types/public/common.ts
- packages/discordx/src/util/common.ts
> feat: `@Reaction`

- packages/discordx/README.md
Simple grammar fix for guards section of main readme
- discordx
> fix grammar in main readme

- packages/di/src/index.ts
> fix: add missed export of di logic

- packages/discordx/src/util/comparison.ts
fixed issue with bigint seralisation, offload chain of responsibility to DJS 
discordx
> fix: fixed seralisation of bigint

- .deepsource.toml
Adds config for deepsource -
- docker and static code analysis, 
- auto prettier fix
- secrets detection
> refactor: update .deepsource

- README.md
- docs/docs/decorators/commands/slash.md
- docs/docs/general/client.md
- docs/docs/general/sharding.md
- docs/docs/installation.mdx
- packages/changelog/README.md
- packages/create-discordx/README.md
- packages/di/README.md
- packages/discordx/README.md
- packages/importer/README.md
- packages/internal/README.md
- packages/koa/README.md
- packages/lava-player/README.md
- packages/lava-queue/README.md
- packages/music/README.md
- packages/pagination/README.md
- packages/socket.io/README.md
- packages/utilities/README.md
> docs: update README's

- packages/discordx/examples/event/commands/rest.ts
- packages/discordx/src/Client.ts
- packages/discordx/src/decorators/classes/DOn.ts
- packages/discordx/src/decorators/decorators/On.ts
- packages/discordx/src/decorators/decorators/Once.ts
- packages/discordx/src/logic/metadata/MetadataStorage.ts
- packages/discordx/src/types/public/common.ts
Added
```ts
@On.rest({ event: "RateLimited" })
```
discordx
> feat: support rest events

- packages/discordx/examples/event/commands/priority.ts
- packages/discordx/src/Client.ts
- packages/discordx/src/decorators/classes/DOn.ts
- packages/discordx/src/decorators/decorators/On.ts
- packages/discordx/src/decorators/decorators/Once.ts
- packages/discordx/src/logic/metadata/MetadataStorage.ts
- packages/discordx/src/types/public/common.ts
add priority on events
discordx
> feat(discordx): add priority sort on events

- docs/docs/discordx/decorators/command/slash-option.md
Remove automatic types, they are no longer needed
> docs: slash-option

- docs/docs/discordx/basics/dependencyInjection.md
- docs/docs/discordx/decorators/command/slash-choice.md
- docs/docs/discordx/decorators/command/slash-group.md
- docs/docs/discordx/decorators/command/slash-option.md
- docs/docs/discordx/decorators/command/slash.md
- docs/docs/discordx/decorators/general/discord.md
- docs/docs/discordx/decorators/general/guard.md
- docs/docs/discordx/decorators/general/guild.md
- docs/docs/discordx/decorators/gui/button-component.md
- docs/docs/discordx/decorators/gui/modal-component.md
- packages/discordx/README.md
> docs: slash and slash-option required fields

- packages/discordx/src/Client.ts
Logs should not be logged in silent mode.
discordx
> refactor(discordx): button handler logs

- packages/discordx/src/Client.ts
- packages/discordx/src/types/public/common.ts
> refactor(discordx): improve logs

- docs/docs/discordx/basics/client.md
- docs/docs/discordx/decorators/general/reaction.md
Thank you for this amazing framework :D makes bot dev more fun. Found some partials type errors on docs while working!
> docs: update outdated docs on partials

- packages/discordx/src/Client.ts
- The guild check should be kept out of the not found error.
- Remove guild check from context menu, as context menu registered on init.
- discordx
> refactor(discordx): improve execution of components and context

- packages/discordx/README.md
website https://discordx.js.org/docs/discordx wasn't formatting the link
> Fix md format

- docs/docs/discordx/decorators/command/slash-option.md
- packages/discordx/examples/slash/commands/transformer.ts
updated transformer example with interaction as second argument. Gives more clarity.
discordx
> docs: update transformer example

- packages/create-discordx/package.json
- packages/lava-player/package.json
- packages/lava-queue/package.json
- packages/pagination/package.json
- packages/utilities/package.json
> chore: dep update

- packages/discordx/src/Client.ts
- Removed unnecessary parameter for simple command execution
```diff
client.executeCommand(
message: Message,
- options?: {
-  caseSensitive?: boolean;
-  forcePrefixCheck?: boolean;
-   log?: boolean;
- }
+ caseSensitive?: boolean
```
- discordx
> refactor: simple command execution

- docs/docs/discordx/basics/client.md
- docs/docs/discordx/getting-started.mdx
- Removed parameters
- added example
> docs: client

- docs/docs/faq/Errors/Common.md
Previous URL was 404 & removed extra bracket
> docs: URL typo & extra bracket

- .github/workflows/Auto Deprecate.yml
- .github/workflows/Build - Documentation.yml
- .github/workflows/Builld.yml
- .github/workflows/Publish - Dev.yml
- .github/workflows/Publish - Documentation.yml
- .github/workflows/Publish - Stable.yml
> chore: workflow node 16

- packages/changelog/src/helper-tag.ts
- packages/discordx/src/Client.ts
- packages/discordx/src/logic/metadata/MetadataStorage.ts
- packages/discordx/src/util/comparison.ts
- packages/discordx/src/util/resolve-guilds.ts
- packages/lava-queue/src/queue.ts
- packages/music/src/core/Queue.ts
- packages/pagination/src/Pagination.ts
This prevents the whole of lodash being imported when bundling.
Replaces https://github.com/discordx-ts/discordx/pull/929 with a signed commit.
- discordx
- @discordx/music
- @discordx/utilities
> chore: make lodash imports tree-shakable

- packages/changelog/src/helper-tag.ts
- packages/discordx/src/Client.ts
- packages/discordx/src/logic/metadata/MetadataStorage.ts
- packages/discordx/src/util/comparison.ts
- packages/discordx/src/util/resolve-guilds.ts
- packages/lava-queue/src/queue.ts
- packages/music/src/core/Queue.ts
- packages/pagination/src/Pagination.ts
> fix(discordx): fix #931

- packages/pagination/README.md
**Please describe the changes this PR makes and why it should be merged:** Fixed typo, import that doesn't exist in beginner code example
> @discordx/pagination
> docs: Fixed Example MessageOptions -> PaginationItem

- packages/discordx/CHANGELOG.md
- packages/discordx/examples/event/main.ts
- packages/discordx/examples/guards/main.ts
- packages/discordx/package.json
- packages/discordx/src/Client.ts
- packages/discordx/src/types/core/common.ts
- packages/utilities/CHANGELOG.md
- packages/utilities/package.json
Added two methods to client `initEvents` and `removeEvents`
> refactor: added initEvents and removeEvents for binding discordx events

- .github/workflows/Publish - Changeset.yml
- package.json
Updated the changesets workflow to use the changesets action so it creates a pull request and when the pull request is merged it will publish any updated packages.
> ci: update changesets workflow

- packages/lava-queue/CHANGELOG.md
- packages/lava-queue/examples/commands/music.cmd.ts
- packages/lava-queue/examples/commands/queue.ts
- packages/lava-queue/package.json
- packages/lava-queue/src/queue.ts
> refactor(lava-queue): addTrack method

- package-lock.json
- packages/lava-queue/CHANGELOG.md
- packages/lava-queue/package.json
- packages/lava-queue/src/queue.ts
- packages/plugin-lava-player/CHANGELOG.md
- packages/plugin-lava-player/README.md
- packages/plugin-lava-player/examples/main.ts
- packages/plugin-lava-player/package.json
- packages/plugin-lava-player/src/commands/play.ts
- packages/plugin-lava-player/src/core/queue.ts
- packages/plugin-lava-player/src/plugins/lavalyrics/index.ts
- packages/plugin-lava-player/src/plugins/lavalyrics/types.ts
Implements the integration with lavalink lyrics endpoint along with examples of how to use it
> refactor(plugin-lava-player):  add lyrics plugin

- packages/create-discordx/CHANGELOG.md
- packages/create-discordx/package.json
- packages/create-discordx/src/helper/package-manager.ts
RE: Since bun is now platform-agnostic and is no longer in BETA, I have added it as a package manager
**Please describe the changes this PR makes:**
Added bun as one of the package mangers for the create-discordx package
> feat: added bun as a package manager
